package com.cetpainfotech.day9;

public class ExceptionDemo4 {
	public static void main(String[] args) {
		
		try
		{
			int a = 6;
			int b =2;
			int c = a/b;
			
			int arr[] = {1,2,4};
			System.out.println(arr[3]);
			
		 }catch (ArithmeticException e) {
			
			 System.out.println("Devide by zero");
		}catch (ArrayIndexOutOfBoundsException e) {
			// TODO: handle exception
		}
		
		System.out.println("End");
		
	}

}
